import Head from 'next/head';
import Image from 'next/image';
import HomePage from '../components/HomePage';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Relivve</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <HomePage />
      </div>
    </div>
  );
}
